---
apiVersion: v1
kind: Namespace
metadata:
  name: slurm
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: slurmdbd
  namespace: slurm
spec:
  selector:
    matchLabels:
      app: slurmdbd
  template:
    metadata:
      labels:
        app: slurmdbd
    spec:
      containers:
      - name: slurmdbd
        image: rkhoja/vulcan-slurm:slurmdbd
        imagePullPolicy: Always
        ports:
        - containerPort: 6819
        volumeMounts:
        - name: host-slurm
          mountPath: /etc/slurm
          readOnly: true
        - name: host-munge
          mountPath: /etc/munge/.secret/
          readOnly: true
      volumes:
      - name: host-slurm
        hostPath:
          path: /etc/slurm
          type: Directory
      - name: host-munge
        hostPath:
          path: /etc/munge/
          type: Directory
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: slurmdbd-service
  namespace: slurm
  labels:
    app: slurmdbd
spec:
  selector:
    app: slurmdbd
  ports:
  - name: slurmdbd
    port: 6819
    protocol: TCP
    targetPort: 6819
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours
  type: ClusterIP
