apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: slurmctld-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.22-192.168.1.22

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: slurmctld-advertisement
  namespace: metallb-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slurmctld
  namespace: slurm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slurmctld
  template:
    metadata:
      labels:
        app: slurmctld
    spec:
      hostname: slurmctld-1
      containers:
      - name: slurmctld
        image: rkhoja/slurm:slurmctld  # Adjust image as needed
        imagePullPolicy: Always
        ports:
        - containerPort: 6817
        volumeMounts:
        - name: nfs-munge-key
          mountPath: /etc/munge/.secret/
        - name: slurm-config
          mountPath: /etc/slurm
        - name: slurmctld-state
          mountPath: /var/spool/slurmctld
        - name: sssd-config
          mountPath: /etc/sssd
        # Uncomment if you need a debug hold:
        # command: ["/bin/bash", "-c"]
        # args:
        #   - |
        #     tail -f /dev/null
      volumes:
      - name: nfs-munge-key
        nfs:
          server: 192.168.1.1
          path: /disks/slurm/etc/munge
      - name: slurm-config
        nfs:
          server: 192.168.1.1
          path: /disks/slurm/etc/slurm
      - name: slurmctld-state
        nfs:
          server: 192.168.1.1
          path: /disks/slurm/var/spool/slurmctld/
      - name: sssd-config
        nfs:
          server: 192.168.1.1
          path: /disks/slurm/etc/sssd
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "slurmctld-1"
---
apiVersion: v1
kind: Service
metadata:
  name: slurmctld-service
  namespace: slurm
  labels:
    app: slurmctld-service
spec:
  selector:
    app: slurmctld
  ports:
  - name: slurmctld
    port: 6817
    protocol: TCP
    targetPort: 6817
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: LoadBalancer
  loadBalancerIP: 192.168.1.22
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerSourceRanges:  # <--- Add this to restrict access to internal IPs
    - 192.168.1.0/24
